namespace com.hafthor.Measurement;

[Measurement("J", VariableName = "joules")]
[SiUnit("Joules", 0, "None Giga Mega Kilo Milli")]
[SiUnit("Ergs", -7)]
[Unit("Kilocalories", 4184)]
[Unit("Calories", 4.184)]
[Unit("KilowattHours", 3.6e6)]
[Unit("WattHours", 3600)]
[Unit("Electronvolts", 1.602176634e-19)]
[Unit("BritishThermalUnits", 1055.05585262)]
[Unit("FootPounds", 1.3558179483314004)]
[Unit("TonsOfTnt", 4.184e9)]
[Product<Force, Length>(Primary = true)]
[Product<Power, Duration>]
[Product<Momentum, Speed>]
[Product<ElectricCharge, Voltage>]
[Product<Pressure, Volume>]
[Product<HeatCapacity, Temperature>]
[Product<Action, Frequency>]
[Product<Frequency, Action>]
[Product<Speed, Momentum>]
public readonly partial struct Energy { }
