using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Measurement.Generators;

// Emits the identical-across-every-measurement boilerplate (operators, equality, comparison,
// formatting, math utilities, and the IMeasurement<T> / System.Numerics surface) into each
// [Measurement]-annotated readonly partial struct, so the hand-written source only needs the
// unit-specific From/To methods and cross-type operators.
[Generator]
public sealed class MeasurementGenerator : IIncrementalGenerator {
    private const string AttrMetadataName = "com.hafthor.Measurement.MeasurementAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrMetadataName,
            predicate: static (node, _) => node is StructDeclarationSyntax,
            transform: static (ctx, _) => {
                var type = (INamedTypeSymbol)ctx.TargetSymbol;
                var symbol = ctx.Attributes[0].ConstructorArguments.Length > 0
                    ? ctx.Attributes[0].ConstructorArguments[0].Value as string ?? ""
                    : "";
                double displayFactor = 1;
                foreach (var na in ctx.Attributes[0].NamedArguments)
                    if (na.Key == "DisplayFactor" && na.Value.Value is double d)
                        displayFactor = d;
                return (Name: type.Name, Namespace: type.ContainingNamespace.ToDisplayString(), Symbol: symbol, DisplayFactor: displayFactor);
            });

        context.RegisterSourceOutput(types, static (ctx, info) =>
            ctx.AddSource(info.Name + ".g.cs", SourceText.From(Emit(info.Name, info.Namespace, info.Symbol, info.DisplayFactor), Encoding.UTF8)));
    }

    private static string Emit(string name, string ns, string symbol, double displayFactor) {
        string disp = displayFactor == 1d
            ? "value"
            : $"(value / {displayFactor.ToString("R", System.Globalization.CultureInfo.InvariantCulture)})";
        string toStr = symbol.Length == 0 ? $"$\"{{{disp}}}\"" : $"$\"{{{disp}}} {symbol}\"";
        string toStrFmt = symbol.Length == 0
            ? $"({disp}).ToString(format, provider)"
            : $"({disp}).ToString(format, provider) + \" {symbol}\"";

        return $@"// <auto-generated/>
#nullable disable
using System;
using System.Numerics;

namespace {ns};

public readonly partial struct {name}
    : IMeasurement<{name}>, IComparable<{name}>, IComparable, IEquatable<{name}>, IFormattable {{
    private readonly double value;
    private {name}(double value) => this.value = value;

    public static {name} FromCanonical(double value) => new {name}(value);
    public double CanonicalValue => value;
    public static {name} Zero => new {name}(0);

    public override string ToString() => {toStr};
    public string ToString(string format, IFormatProvider provider) => {toStrFmt};

    public override bool Equals(object obj) => obj is {name} o && o.value == value;
    public bool Equals({name} other) => other.value == value;
    public override int GetHashCode() => value.GetHashCode();

    public bool NearlyEquals({name} other, int ulps = 4) => MeasurementMath.NearlyEqual(value, other.value, ulps);

    public int CompareTo({name} other) => value.CompareTo(other.value);
    int IComparable.CompareTo(object obj)
        => obj is null ? 1
         : obj is {name} o ? value.CompareTo(o.value)
         : throw new ArgumentException(""Object must be of type {name}."", nameof(obj));

    public static {name} operator +({name} a, {name} b) => new {name}(a.value + b.value);
    public static {name} operator -({name} a, {name} b) => new {name}(a.value - b.value);
    public static {name} operator -({name} a) => new {name}(-a.value);
    public static {name} operator *({name} a, double factor) => new {name}(a.value * factor);
    public static {name} operator *(double factor, {name} a) => new {name}(factor * a.value);
    public static {name} operator /({name} a, double divisor) => new {name}(a.value / divisor);
    public static double operator /({name} a, {name} b) => a.value / b.value;
    public static bool operator <({name} a, {name} b) => a.value < b.value;
    public static bool operator >({name} a, {name} b) => a.value > b.value;
    public static bool operator <=({name} a, {name} b) => a.value <= b.value;
    public static bool operator >=({name} a, {name} b) => a.value >= b.value;
    public static bool operator ==({name} a, {name} b) => a.value == b.value;
    public static bool operator !=({name} a, {name} b) => a.value != b.value;

    public {name} Abs() => new {name}(Math.Abs(value));
    public {name} Min({name} other) => value <= other.value ? this : other;
    public {name} Max({name} other) => value >= other.value ? this : other;
    public {name} Clamp({name} min, {name} max) => new {name}(Math.Clamp(value, min.value, max.value));
    public static {name} Lerp({name} a, {name} b, double t) => new {name}(a.value + (b.value - a.value) * t);
}}
";
    }
}
